### ISSUE TITLE
Problems starting k3x

### ISSUE THREAD

**Issue by hanpov** [inercia/k3x#30]
I'm seeing the following stacktrace when trying to run k3x:
```
GI search path:
[PRE-MAIN]  [search-path] - /usr/lib/x86_64-linux-gnu/girepository-1.0
[PRE-MAIN]  [search-path] - /app/lib/girepository-1.0
[PRE-MAIN]  [search-path] - /app/lib/girepository-1.0
[PRE-MAIN] Current LD_LIBRARY_PATH: 

** (k3x:2): WARNING **: 04:48:33.932: Failed to load shared library 'libgranite.so.5.4.0' referenced by the typelib: libgranite.so.5.4.0: cannot open shared object file: No such file or directory
/usr/lib/python3.7/site-packages/gi/types.py:220: Warning: cannot derive 'k3x+utils_ui+SettingsPage' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/app/bin/k3x", line 61, in <module>
    from k3x import main
  File "/app/share/k3x/k3x/main.py", line 41, in <module>
    from .docker import DockerController
  File "/app/share/k3x/k3x/docker.py", line 31, in <module>
    from .utils_ui import show_notification
  File "/app/share/k3x/k3x/utils_ui.py", line 237, in <module>
    class SettingsPage(Granite.SimpleSettingsPage):
  File "/usr/lib/python3.7/site-packages/gi/types.py", line 229, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3.7/site-packages/gi/types.py", line 208, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3.7/site-packages/gi/types.py", line 220, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: k3x+utils_ui+SettingsPage (subclass of void)
```

I'm running arch linux with KDE. 
What caught my eye was that LD_LIBRARY_PATH env that's empty. Any ideia on how to get it to run?

**Comment by shane-ns1** [comment]
I have the same issue, running Fedora Core 38 with Gnome. I'm not feeling optimistic about a solution since this issue is more than a year old, but I thought that I would report it. :wink:
